# Generated by Django 3.0.7 on 2020-06-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_functions',
        ),
    ]
