# Generated by Django 3.0.7 on 2020-06-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobs_job_functions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_functions',
        ),
        migrations.AddField(
            model_name='jobs',
            name='applied_by',
            field=models.ManyToManyField(related_name='applicants', to='jobs.Applicant'),
        ),
    ]
