# Generated by Django 3.0.7 on 2020-06-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200617_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='applied_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='applicants', to='jobs.Applicant'),
        ),
    ]
