# Generated by Django 3.0.7 on 2020-06-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200617_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='applied_by',
            field=models.ManyToManyField(related_name='applicants', to='jobs.Applicant'),
        ),
    ]
