# Generated by Django 3.0.7 on 2020-06-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200619_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='tags',
        ),
    ]
