# Generated by Django 3.0.7 on 2020-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobs_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.CharField(default='B.E, MBA Finance', max_length=100),
            preserve_default=False,
        ),
    ]
