# Generated by Django 3.0.7 on 2020-06-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_applicant_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='age',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
